<a href="https://colab.research.google.com/github/samsonkinyanjui/Human-Trafficking/blob/main/Human_Trafficking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import os

In [34]:
df=pd.read_csv('/content/human_trafficking.csv')
df.head()

<ipython-input-34-3c6232354257>:1: DtypeWarning: Columns (54) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/human_trafficking.csv')

,yearOfRegistration,Datasource,gender,ageBroad,majorityStatus,majorityStatusAtExploit,majorityEntry,citizenship,meansOfControlDebtBondage,meansOfControlTakesEarnings,...,typeOfSexPrivateSexualServices,typeOfSexConcatenated,isAbduction,RecruiterRelationship,CountryOfExploitation,recruiterRelationIntimatePartner,recruiterRelationFriend,recruiterRelationFamily,recruiterRelationOther,recruiterRelationUnknown
0,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
1,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
2,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
3,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
4,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1

In [23]:
df.columns

Index(['yearOfRegistration', 'Datasource', 'gender', 'ageBroad',
       'majorityStatus', 'majorityStatusAtExploit', 'majorityEntry',
       'citizenship', 'meansOfControlDebtBondage',
       'meansOfControlTakesEarnings', 'meansOfControlRestrictsFinancialAccess',
       'meansOfControlThreats', 'meansOfControlPsychologicalAbuse',
       'meansOfControlPhysicalAbuse', 'meansOfControlSexualAbuse',
       'meansOfControlFalsePromises', 'meansOfControlPsychoactiveSubstances',
       'meansOfControlRestrictsMovement', 'meansOfControlRestrictsMedicalCare',
       'meansOfControlExcessiveWorkingHours', 'meansOfControlUsesChildren',
       'meansOfControlThreatOfLawEnforcement',
       'meansOfControlWithholdsNecessities',
       'meansOfControlWithholdsDocuments', 'meansOfControlOther',
       'meansOfControlNotSpecified', 'meansOfControlConcatenated',
       'isForcedLabour', 'isSexualExploit', 'isOtherExploit', 'isSexAndLabour',
       'isForcedMarriage', 'isForcedMilitary', 'isOrganRemoval',
       'isSlaveryAndPractices', 'typeOfExploitConcatenated',
       'typeOfLabourAgriculture', 'typeOfLabourAquafarming',
       'typeOfLabourBegging', 'typeOfLabourConstruction',
       'typeOfLabourDomesticWork', 'typeOfLabourHospitality',
       'typeOfLabourIllicitActivities', 'typeOfLabourManufacturing',
       'typeOfLabourMiningOrDrilling', 'typeOfLabourPeddling',
       'typeOfLabourTransportation', 'typeOfLabourOther',
       'typeOfLabourNotSpecified', 'typeOfLabourConcatenated',
       'typeOfSexProstitution', 'typeOfSexPornography',
       'typeOfSexRemoteInteractiveServices', 'typeOfSexPrivateSexualServices',
       'typeOfSexConcatenated', 'isAbduction', 'RecruiterRelationship',
       'CountryOfExploitation', 'recruiterRelationIntimatePartner',
       'recruiterRelationFriend', 'recruiterRelationFamily',
       'recruiterRelationOther', 'recruiterRelationUnknown'],
      dtype='object')

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48801 entries, 0 to 48800
Data columns (total 63 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   yearOfRegistration                      48801 non-null  int64
 1   Datasource                              48801 non-null  object
 2   gender                                  48801 non-null  object
 3   ageBroad                                48801 non-null  object
 4   majorityStatus                          48801 non-null  object
 5   majorityStatusAtExploit                 48801 non-null  object
 6   majorityEntry                           48801 non-null  object
 7   citizenship                             48801 non-null  object
 8   meansOfControlDebtBondage               48801 non-null  int64
 9   meansOfControlTakesEarnings             48801 non-null  int64
 10  meansOfControlRestrictsFinancialAccess  48801 non-null  int64
 11  meansOfControlThreats                   48801 non-null  int64
 12  meansOfControlPsychologicalAbuse        48801 non-null  int64
 13  meansOfControlPhysicalAbuse             48801 non-null  int64
 14  meansOfControlSexualAbuse               48801 non-null  int64
 15  meansOfControlFalsePromises             48801 non-null  int64
 16  meansOfControlPsychoactiveSubstances    48801 non-null  int64
 17  meansOfControlRestrictsMovement         48801 non-null  int64
 18  meansOfControlRestrictsMedicalCare      48801 non-null  int64
 19  meansOfControlExcessiveWorkingHours     48801 non-null  int64
 20  meansOfControlUsesChildren              48801 non-null  int64
 21  meansOfControlThreatOfLawEnforcement    48801 non-null  int64
 22  meansOfControlWithholdsNecessities      48801 non-null  int64
 23  meansOfControlWithholdsDocuments        48801 non-null  int64
 24  meansOfControlOther                     48801 non-null  int64
 25  meansOfControlNotSpecified              48801 non-null  int64
 26  meansOfControlConcatenated              48801 non-null  object
 27  isForcedLabour                          48801 non-null  int64
 28  isSexualExploit                         48801 non-null  int64
 29  isOtherExploit                          48801 non-null  int64
 30  isSexAndLabour                          48801 non-null  int64
 31  isForcedMarriage                        48801 non-null  int64
 32  isForcedMilitary                        48801 non-null  int64
 33  isOrganRemoval                          48801 non-null  int64
 34  isSlaveryAndPractices                   48801 non-null  int64
 35  typeOfExploitConcatenated               48801 non-null  object
 36  typeOfLabourAgriculture                 48801 non-null  int64
 37  typeOfLabourAquafarming                 48801 non-null  int64
 38  typeOfLabourBegging                     48801 non-null  int64
 39  typeOfLabourConstruction                48801 non-null  int64
 40  typeOfLabourDomesticWork                48801 non-null  int64
 41  typeOfLabourHospitality                 48801 non-null  int64
 42  typeOfLabourIllicitActivities           48801 non-null  int64
 43  typeOfLabourManufacturing               48801 non-null  int64
 44  typeOfLabourMiningOrDrilling            48801 non-null  int64
 45  typeOfLabourPeddling                    48801 non-null  int64
 46  typeOfLabourTransportation              48801 non-null  int64
 47  typeOfLabourOther                       48801 non-null  int64
 48  typeOfLabourNotSpecified                48801 non-null  int64
 49  typeOfLabourConcatenated                48801 non-null  object
 50  typeOfSexProstitution                   48801 non-null  int64
 51  typeOfSexPornography                    48801 non-null  int64
 52  typeOfSexRemoteInteractiveServices      48801 non-null  int64
 53  typeOfSexPrivateSexualServices          48801 non-null  int64
 54  typeOfSexConcatenated                   48801 non-null  object
 55  isAbduction                             48801 non-null  int64
 56  RecruiterRelationship                   48801 non-null  object
 57  CountryOfExploitation                   48801 non-null  object
 58  recruiterRelationIntimatePartner        48801 non-null  int64
 59  recruiterRelationFriend                 48801 non-null  int64
 60  recruiterRelationFamily                 48801 non-null  int64
 61  recruiterRelationOther                  48801 non-null  int64
 62  recruiterRelationUnknown                48801 non-null  int64
dtypes: int64(50), object(13)
memory usage: 23.5+ MB

In [25]:
# 1. Dataset Overview
print("Dataset Shape:", df.shape)
print("\nData Types:\n", df.dtypes)
print("\nMissing Values:\n", df.isnull().sum())

Dataset Shape: (48801, 63)

Data Types:
 yearOfRegistration                   int64
Datasource                          object
gender                              object
ageBroad                            object
majorityStatus                      object
                                     ...
recruiterRelationIntimatePartner     int64
recruiterRelationFriend              int64
recruiterRelationFamily              int64
recruiterRelationOther               int64
recruiterRelationUnknown             int64
Length: 63, dtype: object

Missing Values:
 yearOfRegistration                  0
Datasource                          0
gender                              0
ageBroad                            0
majorityStatus                      0
                                   ..
recruiterRelationIntimatePartner    0
recruiterRelationFriend             0
recruiterRelationFamily             0
recruiterRelationOther              0
recruiterRelationUnknown            0
Length: 63, dtype: int64

In [26]:
# 2. Replace -99 with NaN for meaningful analysis
df.replace(-99, pd.NA, inplace=True)

In [27]:
# 3. Summary Statistics (for numerical columns)
print("\nSummary Statistics:\n", df.describe())

Summary Statistics:
        yearOfRegistration
count        48801.000000
mean          2014.144218
std              4.025566
min           2002.000000
25%           2013.000000
50%           2016.000000
75%           2017.000000
max           2019.000000

In [28]:
# 4. Categorical Feature Distribution
categorical_columns = ['gender', 'ageBroad', 'Datasource', 'citizenship', 'majorityStatus']
for col in categorical_columns:
    print(f"\n{col} Distribution:\n", df[col].value_counts())

gender Distribution:
 gender
Female    35534
Male      13267
Name: count, dtype: int64

ageBroad Distribution:
 ageBroad
-99       12362
9--17      8645
30--38     7091
18--20     4448
21--23     4213
24--26     3464
39--47     2821
27--29     2641
48+        1560
0--8       1556
Name: count, dtype: int64

Datasource Distribution:
 Datasource
Case Management    36289
Hotline            12512
Name: count, dtype: int64

citizenship Distribution:
 citizenship
PH     11365
00      8858
UA      7761
MD      5901
US      3636
KH      1979
ID      1971
BY      1463
MM      1250
RO       655
GH       544
KG       437
BG       342
HT       339
-99      278
UZ       261
VN       170
GW       145
LA       126
CO       124
NG       108
UG        98
AF        97
MG        94
LK        85
SL        81
SN        70
TH        55
KZ        54
CD        53
ML        45
TJ        43
BF        33
KE        32
NE        31
CI        31
NP        27
TM        26
CN        23
AL        22
MX        19
BO        18
GN        15
ER        13
KR        12
BD        11
Name: count, dtype: int64

majorityStatus Distribution:
 majorityStatus
Adult    26238
-99      12362
Minor    10201
Name: count, dtype: int64

In [31]:
# Save the cleaned dataset as a new CSV file
df.to_csv('new_human_trafficking.csv', index=False)

In [35]:
df2=pd.read_csv('/content/new_human_trafficking.csv')
df2.head()

<ipython-input-35-6beeb78c696c>:1: DtypeWarning: Columns (54) have mixed types. Specify dtype option on import or set low_memory=False.
  df2=pd.read_csv('/content/new_human_trafficking.csv')

,yearOfRegistration,Datasource,gender,ageBroad,majorityStatus,majorityStatusAtExploit,majorityEntry,citizenship,meansOfControlDebtBondage,meansOfControlTakesEarnings,...,typeOfSexPrivateSexualServices,typeOfSexConcatenated,isAbduction,RecruiterRelationship,CountryOfExploitation,recruiterRelationIntimatePartner,recruiterRelationFriend,recruiterRelationFamily,recruiterRelationOther,recruiterRelationUnknown
0,2002,Case Management,Female,18--20,Adult,-99,-99,CO,NaN,NaN,...,NaN,NaN,NaN,-99,-99,0.0,0.0,0.0,0.0,1.0
1,2002,Case Management,Female,18--20,Adult,-99,-99,CO,NaN,NaN,...,NaN,NaN,NaN,-99,-99,0.0,0.0,0.0,0.0,1.0
2,2002,Case Management,Female,18--20,Adult,-99,-99,CO,NaN,NaN,...,NaN,NaN,NaN,-99,-99,0.0,0.0,0.0,0.0,1.0
3,2002,Case Management,Female,18--20,Adult,-99,-99,CO,NaN,NaN,...,NaN,NaN,NaN,-99,-99,0.0,0.0,0.0,0.0,1.0
4,2002,Case Management,Female,18--20,Adult,-99,-99,CO,NaN,NaN,...,NaN,NaN,NaN,-99,-99,0.0,0.0,0.0,0.0,1.0

In [36]:
# 1. Replace -99 with NaN for meaningful analysis
df.replace(-99, pd.NA, inplace=True)

In [37]:
df.head()

,yearOfRegistration,Datasource,gender,ageBroad,majorityStatus,majorityStatusAtExploit,majorityEntry,citizenship,meansOfControlDebtBondage,meansOfControlTakesEarnings,...,typeOfSexPrivateSexualServices,typeOfSexConcatenated,isAbduction,RecruiterRelationship,CountryOfExploitation,recruiterRelationIntimatePartner,recruiterRelationFriend,recruiterRelationFamily,recruiterRelationOther,recruiterRelationUnknown
0,2002,Case Management,Female,18--20,Adult,-99,-99,CO,<NA>,<NA>,...,<NA>,<NA>,<NA>,-99,-99,0,0,0,0,1
1,2002,Case Management,Female,18--20,Adult,-99,-99,CO,<NA>,<NA>,...,<NA>,<NA>,<NA>,-99,-99,0,0,0,0,1
2,2002,Case Management,Female,18--20,Adult,-99,-99,CO,<NA>,<NA>,...,<NA>,<NA>,<NA>,-99,-99,0,0,0,0,1
3,2002,Case Management,Female,18--20,Adult,-99,-99,CO,<NA>,<NA>,...,<NA>,<NA>,<NA>,-99,-99,0,0,0,0,1
4,2002,Case Management,Female,18--20,Adult,-99,-99,CO,<NA>,<NA>,...,<NA>,<NA>,<NA>,-99,-99,0,0,0,0,1