<a href="https://colab.research.google.com/github/samsonkinyanjui/Human-Trafficking/blob/main/Neoj4Human_Trafficking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import os

In [3]:
# List of your CSV file names
csv_list = [
    "2013_competent_authority.csv", "2014_referrals_all.csv", "2016_competent_authority.csv",
    "2013_country_of_referral.csv", "2014_referrals_minor.csv", "2016_country_of_referral.csv",
    "2013_exploitation_type.csv", "2014_referring_agency.csv", "2016_decision_data.csv",
    "2013_referrals_adult.csv", "2015_competent_authority.csv", "2016_exploitation_type.csv",
    "2013_referrals_all.csv", "2015_country_of_referral.csv", "2016_referrals_adult.csv",
    "2013_referrals_minor.csv", "2015_decision_data.csv", "2016_referrals_all.csv",
    "2013_referring_agency.csv", "2015_exploitation_type.csv", "2016_referrals_minor.csv",
    "2014_competent_authority.csv", "2015_referrals_adult.csv", "2016_referring_agency.csv",
    "2014_country_of_referral.csv", "2015_referrals_all.csv",
    "2014_exploitation_type.csv", "2015_referrals_minor.csv", "2014_referrals_adult.csv",
    "2015_referring_agency.csv"
]

In [4]:
# Function to iterate through the files and display their columns
def read_and_display_columns(csv_files, directory='/content/'):
    for file_name in csv_files:
        file_path = os.path.join(directory, file_name) if directory else file_name
        try:
            # Read the CSV file
            df = pd.read_csv(file_path)
            print(f"Columns for file {file_name}:")
            print(df.columns)
            print("Preview of the data:")
            print(df.head(), "\n")
        except Exception as e:
            print(f"Error reading file {file_name}: {e}")

# Assuming files are in the current directory; adjust `directory` if necessary
read_and_display_columns(csv_list)

Columns for file 2013_competent_authority.csv:
Index(['Competent Authority', 'Total', '% Total', '2012 - 2013% Change'], dtype='object')
Preview of the data:
               Competent Authority  Total % Total 2012 - 2013% Change
0      Home Office (Formerly UKBA)   1032     59%                 33%
1  Home Office hosted within UKHTC    128      7%                 32%
2                            UKHTC    586     34%                 88%
3                            Total   1746     NaN                 NaN

Columns for file 2014_referrals_all.csv:
Index(['Country of Origin', 'Female', 'Male', 'Transgender', 'Total',
       '2013 - 2014 % Change'],
      dtype='object')
Preview of the data:
  Country of Origin Female  Male  Transgender Total 2013 - 2014 % Change
0           Albania    351    98            0   449                  68%
1           Nigeria    204    40            0   244                  31%
2           Vietnam     76   140            0   216                  19%
3           Romania     68    83            0   151                  45%
4          Slovakia     69    63            0   132                 136%

Columns for file 2016_competent_authority.csv:
Index(['Competent Authority', 'Total', '% of Total', '2015 - 2016 % Change'], dtype='object')
Preview of the data:
                                 Competent Authority  Total % of Total  \
0        Home Office UK Visas and Immigration (UKVI)   2729     71.70%
1  Home Office UKVI hosted within NCA Modern Slav...     18      0.50%
2  NCA Modern Slavery Human Trafficking Unit (MSHTU)    778     20.40%
3  NRM Pilot Cases - Slavery Safeguarding Leads a...    280      7.40%
4                                              Total   3805        NaN

  2015 - 2016 % Change
0               19.10%
1              -86.40%
2               -3.00%
3              582.90%
4                  NaN

Columns for file 2013_country_of_referral.csv:
Index(['Country of NRM referral', 'Female', 'Male', 'Total', '% Total',
       '2012 - 2013% Change'],
      dtype='object')
Preview of the data:
  Country of NRM referral  Female  Male  Total % Total 2012 - 2013% Change
0                 England     994   562   1556     89%                 49%
1        Northern Ireland      25    16     41      2%                173%
2                Scotland      65    34     99      6%                  3%
3                   Wales      38    12     50      3%                 47%
4                   Total    1122   624   1746     NaN                 NaN

Columns for file 2014_referrals_minor.csv:
Index(['Country of Origin', 'Female', 'Male', 'Total', '2013 - 2014 % Change'], dtype='object')
Preview of the data:
  Country of Origin  Female  Male  Total 2013 - 2014 % Change
0           Albania      34    83    117                 109%
1           Vietnam      33    76    109                  43%
2    United Kingdom      70     5     75                  19%
3          Slovakia      42    30     72                1100%
4           Nigeria      38    16     54                  69%

Columns for file 2016_country_of_referral.csv:
Index(['Country of NRM Referral', 'Adult', 'Minor', 'Total', '% of Total',
       '2015 - 2016 % Change'],
      dtype='object')
Preview of the data:
  Country of NRM Referral  Adult  Minor  Total % of Total 2015 - 2016 % Change
0                England    2295   1204   3499        92%               19.20%
1        Northern Ireland     27      6     33      0.90%              -37.70%
2               Scotland     103     47    150      3.90%                3.40%
3                   Wales    102     21    123      3.20%               -8.20%
4                   Total   2527   1278   3805        NaN                  NaN

Columns for file 2013_exploitation_type.csv:
Index(['Claimed exploitation Type', 'Female', 'Male', 'Total',
       '2012 - 2013% Change'],
      dtype='object')
Preview of the data:
      Claimed exploitation Type  Female  Male  Total 2012 - 2013% Change
0    Adult - Domestic Servitude     125    16    141                 18%
1   Adult - Labour Exploitation     124   387    511                 89%
2   Adult - Sexual Exploitation     563    18    581                 53%
3  Adult - Unknown exploitation      42    20     62                 44%
4    Minor - Domestic Servitude      37     8     45                  2%

Columns for file 2014_referring_agency.csv:
Index(['First Responder Organisation', 'Female', 'Male', 'Transgender',
       'Total', 'Type'],
      dtype='object')
Preview of the data:
                   First Responder Organisation  Female  Male  Transgender  \
0  Home Office (UKVI / Immigration Enforcement)     653   284            0
1                        UK Border Force (UKBF)      58    28            0
2               Gangmasters Licensing Authority       1     4            0
3                                           NCA       2     4            0
4                               Local Authority     102    70            0

   Total               Type
0    937  Government Agency
1     86  Government Agency
2      5  Government Agency
3      6  Government Agency
4    172    Local Authority

Columns for file 2016_decision_data.csv:
Index(['Year', 'Total Number of Referrals', 'Positive Conclusive Decisions',
       'Negative (RG or CD)', 'Pending decision (RG or CD)', 'Suspended Cases',
       'Withdrawn'],
      dtype='object')
Preview of the data:
   Year  Total Number of Referrals  Positive Conclusive Decisions  \
0  2013                       1745                            824
1  2014                       2340                            900
2  2015                       3266                           1028
3  2016                       3805                            635

   Negative (RG or CD)  Pending decision (RG or CD)  Suspended Cases  \
0                  776                           16               62
1                 1013                          312               53
2                 1186                          845              120
3                  962                         2053               64

   Withdrawn
0         67
1         62
2         87
3         91

Columns for file 2013_referrals_adult.csv:
Index(['Nationality/ Country of Origin', 'Total', '2012 - 2013% Change'], dtype='object')
Preview of the data:
  Nationality/ Country of Origin  Total 2012 - 2013% Change
0                        Albania    212                106%
1                        Nigeria    154                 12%
2                        Vietnam    105                169%
3                         Poland     82                 58%
4                        Romania     75                 29%

Columns for file 2015_competent_authority.csv:
Index(['Competent Authority', 'Total', '% of Total', '2014 - 2015 % Change'], dtype='object')
Preview of the data:
                                 Competent Authority  Total % of Total  \
0        Home Office UK Visas and Immigration (UKVI)   2291     70.10%
1  Home Office UKVI hosted within NCA UK Human Tr...    132      4.00%
2            NCA UK Human Trafficking Centre (UKHTC)    802     24.60%
3  NRM Pilot cases - Slavery Safeguarding Leads a...     41      1.30%
4                                              Total   3266        NaN

  2014 - 2015 % Change
0               63.20%
1              -37.10%
2               10.50%
3                  NaN
4                  NaN

Columns for file 2016_exploitation_type.csv:
Index(['Claimed Exploitation Type', 'Female', 'Male', 'Trans- gender',
       'Total 2016', '2015 - 2016 % Change'],
      dtype='object')
Preview of the data:
      Claimed Exploitation Type  Female  Male  Trans- gender  Total 2016  \
0    Adult - Domestic Servitude     259    67              0         326
1   Adult - Labour Exploitation     182   925              0        1107
2      Adult - Organ Harvesting       1     0              0           1
3   Adult - Sexual Exploitation     888    58              5         951
4  Adult - Unknown Exploitation      70    72              0         142

  2015 - 2016 % Change
0               -7.60%
1               23.70%
2              -50.00%
3               10.20%
4              -17.00%

Columns for file 2013_referrals_all.csv:
Index(['Nationality/ Country of Origin', 'Female', 'Male', 'Total',
       '2012 - 2013% Change'],
      dtype='object')
Preview of the data:
  Nationality/ Country of Origin  Female  Male  Total 2012 - 2013% Change
0                        Albania     232    36    268                109%
1                        Nigeria     160    26    186                 -9%
2                        Vietnam      81   100    181                 34%
3                        Romania      62    42    104                 41%
4                             UK      64    26     90                173%

Columns for file 2015_country_of_referral.csv:
Index(['Country of NRM referral', 'Adult', 'Minor', 'Total', '% of Total',
       '2014 - 2015 % Change'],
      dtype='object')
Preview of the data:
  Country of NRM referral  Adult  Minor  Total % of Total 2014 - 2015 % Change
0                 England   2033    901   2934     89.80%               38.80%
1        Northern Ireland     40     13     53      1.60%               17.80%
2                Scotland    103     42    145      4.40%               30.60%
3                   Wales    108     26    134      4.10%               91.40%
4                   Total   2284    982   3266        NaN                  NaN

Columns for file 2016_referrals_adult.csv:
Index(['Nationality/ Country of Origin', 'Domestic Servitude',
       'Labour Exploitation', 'Organ Harvesting', 'Sexual Exploitation',
       'Unknown Exploitation', '2016 Total', '2015-2016 % Change'],
      dtype='object')
Preview of the data:
  Nationality/ Country of Origin  Domestic Servitude  Labour Exploitation  \
0                        Albania                   4                   43
1                        Vietnam                  15                  185
2                          China                   7                  129
3                        Nigeria                  58                   29
4                        Romania                   6                  124

   Organ Harvesting  Sexual Exploitation  Unknown Exploitation  2016 Total  \
0                 0                  407                    18         472
1                 0                   67                    25         292
2                 0                   64                    19         219
3                 0                  102                    11         200
4                 0                   41                     4         175

  2015-2016 % Change
0             19.80%
1                27%
2            167.10%
3             -6.50%
4              2.90%

Columns for file 2013_referrals_minor.csv:
Index(['Nationality/ Country of Origin', 'Total', '2012 - 2013% Change'], dtype='object')
Preview of the data:
  Nationality/ Country of Origin  Total 2012 - 2013% Change
0                        Vietnam     76                -21%
1                             UK     63                186%
2                        Albania     56                124%
3                        Nigeria     32                -52%
4                        Romania     28                 75%

Columns for file 2015_decision_data.csv:
Index(['Year', 'Total Number of Referrals', 'Positive Conclusive Decisions',
       'Negative (RG or CD)', 'Pending decision (RG or CD)', 'Suspended Cases',
       'Withdrawn from Process'],
      dtype='object')
Preview of the data:
   Year  Total Number of Referrals  Positive Conclusive Decisions  \
0  2013                       1745                            824
1  2014                       2340                            900
2  2015                       3266                           1028

   Negative (RG or CD)  Pending decision (RG or CD)  Suspended Cases  \
0                  776                           16               62
1                 1013                          312               53
2                 1186                          845              120

   Withdrawn from Process
0                      67
1                      62
2                      87

Columns for file 2016_referrals_all.csv:
Index(['Nationality/ Country of Origin', 'Domestic Servitude',
       'Labour Exploitation', 'Organ Harvesting', 'Sexual Exploitation',
       'Unknown Exploitation', '2016 Total', '2015-2016 % Change'],
      dtype='object')
Preview of the data:
  Nationality/ Country of Origin  Domestic Servitude  Labour Exploitation  \
0                        Albania                   5                  194
1                        Vietnam                  30                  307
2                 United Kingdom                   3                   85
3                        Nigeria                  77                   32
4                          China                  11                  139

   Organ Harvesting  Sexual Exploitation  Unknown Exploitation  2016 Total  \
0                 0                  433                    67         699
1                 0                   88                    94         519
2                 0                  233                     5         326
3                 0                  109                    25         243
4                 0                   67                    24         241

  2015-2016 % Change
0             16.50%
1              8.60%
2             70.70%
3             -5.40%
4            143.40%

Columns for file 2013_referring_agency.csv:
Index(['First Responder Organisation', 'Female', 'Male', 'Total'], dtype='object')
Preview of the data:
  First Responder Organisation  Female  Male  Total
0       Avon & Somerset Police      14     8     22
1                   Barnardo's      20     8     28
2                        BAWSO      11     0     11
3          Bedfordshire Police       3     3      6
4     British Transport Police       1     0      1

Columns for file 2015_exploitation_type.csv:
Index(['Claimed exploitation Type', 'Female', 'Male', 'Transsexual', 'Unknown',
       'Total 2015', '2014 - 2015 % Change'],
      dtype='object')
Preview of the data:
      Claimed exploitation Type  Female  Male  Transsexual  Unknown  \
0    Adult - Domestic Servitude     292    61            0        0
1   Adult - Labour Exploitation     161   734            0        0
2      Adult - Organ Harvesting       1     1            0        0
3   Adult - Sexual Exploitation     813    48            2        0
4  Adult - Unknown exploitation      98    73            0        0

   Total 2015 2014 - 2015 % Change
0         353               50.90%
1         895               53.30%
2           2              100.00%
3         863               28.20%
4         171               -3.40%

Columns for file 2016_referrals_minor.csv:
Index(['Nationality/ Country of Origin', 'Domestic Servitude',
       'Labour Exploitation', 'Sexual Exploitation', 'Unknown Exploitation',
       '2016 Total', '2015-2016 % Change'],
      dtype='object')
Preview of the data:
  Nationality/ Country of Origin  Domestic Servitude  Labour Exploitation  \
0                 United Kingdom                   0                   35
1                        Albania                   1                  151
2                        Vietnam                  15                  122
3                    Afghanistan                   3                   19
4                        Eritrea                  11                   11

   Sexual Exploitation  Unknown Exploitation  2016 Total 2015-2016 % Change
0                  216                     4         255            100.80%
1                   26                    49         227             10.20%
2                   21                    69         227             -8.50%
3                   10                    42          74             80.50%
4                    9                    17          48             14.30%

Columns for file 2014_competent_authority.csv:
Index(['Competent Authority', 'Total', '% of Total', '2013 - 2014 % Change'], dtype='object')
Preview of the data:
                                 Competent Authority  Total % of Total  \
0        Home Office UK Visas and Immigration (UKVI)  1,405        60%
1  Home Office UKVI hosted within NCA UK Human Tr...    210         9%
2            NCA UK Human Trafficking Centre (UKHTC)    725        31%
3                                              Total  2,340        NaN

  2013 - 2014 % Change
0                  36%
1                  64%
2                  24%
3                  NaN

Columns for file 2015_referrals_adult.csv:
Index(['Nationality/ Country of Origin', 'Domestic Servitude',
       'Labour Exploitation', 'Organ Harvesting', 'Sexual Exploitation',
       'Unknown Exploitation', '2015 Total', '2014-2015 % Change'],
      dtype='object')
Preview of the data:
  Nationality/ Country of Origin  Domestic Servitude  Labour Exploitation  \
0                        Albania                   7                   17
1                        Vietnam                  20                  134
2                        Nigeria                  68                   16
3                        Romania                   5                  114
4                         Poland                   4                  139

   Organ Harvesting  Sexual Exploitation  Unknown Exploitation  2015 Total  \
0                 0                  348                    22         394
1                 0                   49                    27         230
2                 0                  112                    18         214
3                 0                   42                     9         170
4                 0                    8                     7         158

  2014-2015 % Change
0             18.70%
1            115.00%
2             12.60%
3             26.90%
4            102.60%

Columns for file 2016_referring_agency.csv:
Index(['Referring Agency', 'Adult', 'Minor', 'Total', 'Agency Type'], dtype='object')
Preview of the data:
                    Referring Agency  Adult  Minor  Total        Agency Type
0  HO Immigration Enforcement (HOIE)    323     51    374  Government Agency
1        National Crime Agency (NCA)      5      0      5  Government Agency
2             UK Border Force (UKBF)     20     91    111  Government Agency
3    UK Visas and Immigration (UKVI)   1044    404   1448  Government Agency
4                    Local Authority     50    368    418    Local Authority

Columns for file 2014_country_of_referral.csv:
Index(['Country of NRM referral', 'Female', 'Male', 'Transgender', 'Total',
       '% of Total', '2013 - 2014 % Change'],
      dtype='object')
Preview of the data:
  Country of NRM referral Female  Male  Transgender  Total % of Total  \
0                 England  1,316   796            2  2,114        90%
1        Northern Ireland     16    29            0     45         2%
2                Scotland     62    49            0    111         5%
3                   Wales     38    32            0     70         3%
4                   Total  1,432   906            2  2,340        NaN

  2013 - 2014 % Change
0                  36%
1                  10%
2                  12%
3                  40%
4                  NaN

Columns for file 2015_referrals_all.csv:
Index(['Nationality/ Country of Origin', 'Domestic Servitude',
       'Labour Exploitation', 'Organ Harvesting', 'Sexual Exploitation',
       'Unknown Exploitation', '2015 Total', '2014-2015 % Change'],
      dtype='object')
Preview of the data:
  Nationality/ Country of Origin  Domestic Servitude  Labour Exploitation  \
0                        Albania                   7                  136
1                        Vietnam                  26                  231
2                        Nigeria                  81                   19

In [9]:
list_csv=csv_list
def merge_csv(list_csv):
    """
    Merge multiple CSV files based on a condition.
    """
    merged_data = pd.DataFrame()

    for file in list_csv:
        # Read the current CSV file
        df = pd.read_csv(file)

        # Extract year from the filename (e.g., "2013" from "2013_competent_authority.csv")
        year = int(file.split("_")[0])
        df['Year'] = year  # Add a Year column

        # Append the data to the merged DataFrame
        merged_data = pd.concat([merged_data, df], ignore_index=True, sort=False)

    return merged_data

In [16]:
def standardize(merged_file):
    """
    Standardize the merged file by renaming columns and handling missing values.
    """
    # Standardized column mapping
    column_mapping = {
        "Country of Origin": "Country",
        "Country of Referral": "Country",
        "Competent Authority": "Authority/Agency",
        "First Responder Organisation": "Authority/Agency",
        "Referring Agency": "Authority/Agency",
        "Female": "Female",
        "Male": "Male",
        "Transgender": "Transgender",
        "Total": "Total Cases",
        "2015 Total": "Total Cases",
        "2016 Total": "Total Cases",
        "% Total": "Percent of Total",
        "% of Total": "Percent of Total",
        "Claimed exploitation Type": "Exploitation Type",
        "Adult": "Adult",
        "Minor": "Minor",
        "2012 - 2013% Change": "Percent Change",
        "2013 - 2014 % Change": "Percent Change",
        "2015 - 2016 % Change": "Percent Change"
    }

    # Rename columns
    standardized_file = merged_file.rename(columns=column_mapping)

    for col in standardized_file.columns:  # Iterate over all columns
        if standardized_file[col].dtypes.name == 'object':  # Handle object (string) columns
            standardized_file[col] = standardized_file[col].fillna('Unknown')
        else:  # Attempt to handle numerical columns
            try:
                # Convert the column to numeric, forcing non-numeric values to NaN
                standardized_file[col] = pd.to_numeric(standardized_file[col], errors='coerce')
                # Now calculate the mean with the numeric-only values
                standardized_file[col] = standardized_file[col].fillna(standardized_file[col].mean())
            except (TypeError, ValueError):
                # If conversion to numeric fails, treat it as a string column
                standardized_file[col] = standardized_file[col].fillna('Unknown')

    return standardized_file

In [17]:
# Perform the merging and standardization
merged_file = merge_csv(list_csv)
standardized_file = standardize(merged_file)

# Save the standardized file
standardized_file.to_csv("final_dataset.csv", index=False)

print("Merged and standardized file saved as 'final_dataset.csv'.")

Merged and standardized file saved as 'final_dataset.csv'.

In [18]:
df=pd.read_csv('/content/final_dataset.csv')
df.head()

,Authority/Agency,Total Cases,Percent of Total,Percent Change,Year,Country,Female,Male,Transgender,Percent Change.1,...,Total Cases.1,2015-2016 % Change,Withdrawn from Process,Transsexual,Unknown,Total 2015,Total Cases.2,2014-2015 % Change,Authority/Agency.2,Agency Type
0,Home Office (Formerly UKBA),1032,59%,33%,2013,Unknown,Unknown,41.66087,0.067416,Unknown,...,Unknown,Unknown,72.0,0.333333,0.333333,544.333333,Unknown,Unknown,Unknown,Unknown
1,Home Office hosted within UKHTC,128,7%,32%,2013,Unknown,Unknown,41.66087,0.067416,Unknown,...,Unknown,Unknown,72.0,0.333333,0.333333,544.333333,Unknown,Unknown,Unknown,Unknown
2,UKHTC,586,34%,88%,2013,Unknown,Unknown,41.66087,0.067416,Unknown,...,Unknown,Unknown,72.0,0.333333,0.333333,544.333333,Unknown,Unknown,Unknown,Unknown
3,Total,1746,Unknown,Unknown,2013,Unknown,Unknown,41.66087,0.067416,Unknown,...,Unknown,Unknown,72.0,0.333333,0.333333,544.333333,Unknown,Unknown,Unknown,Unknown
4,Unknown,449,Unknown,Unknown,2014,Albania,351,98.00000,0.000000,68%,...,Unknown,Unknown,72.0,0.333333,0.333333,544.333333,Unknown,Unknown,Unknown,Unknown

In [21]:
df.shape

(1213, 45)

In [19]:
df.columns

Index(['Authority/Agency', 'Total Cases', 'Percent of Total', 'Percent Change',
       'Year', 'Country', 'Female', 'Male', 'Transgender', 'Percent Change.1',
       'Percent of Total.1', 'Percent Change.2', 'Country of NRM referral',
       'Country of NRM Referral', 'Adult', 'Minor', 'Exploitation Type',
       'Authority/Agency.1', 'Type', 'Total Number of Referrals',
       'Positive Conclusive Decisions', 'Negative (RG or CD)',
       'Pending decision (RG or CD)', 'Suspended Cases', 'Withdrawn',
       'Nationality/ Country of Origin', '2014 - 2015 % Change',
       'Claimed Exploitation Type', 'Trans- gender', 'Total 2016',
       'Domestic Servitude', 'Labour Exploitation', 'Organ Harvesting',
       'Sexual Exploitation', 'Unknown Exploitation', 'Total Cases.1',
       '2015-2016 % Change', 'Withdrawn from Process', 'Transsexual',
       'Unknown', 'Total 2015', 'Total Cases.2', '2014-2015 % Change',
       'Authority/Agency.2', 'Agency Type'],
      dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1213 entries, 0 to 1212
Data columns (total 45 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Authority/Agency                1213 non-null   object
 1   Total Cases                     1213 non-null   object
 2   Percent of Total                1213 non-null   object
 3   Percent Change                  1213 non-null   object
 4   Year                            1213 non-null   int64
 5   Country                         1213 non-null   object
 6   Female                          1213 non-null   object
 7   Male                            1213 non-null   float64
 8   Transgender                     1213 non-null   float64
 9   Percent Change.1                1213 non-null   object
 10  Percent of Total.1              1213 non-null   object
 11  Percent Change.2                1213 non-null   object
 12  Country of NRM referral         1213 non-null   object
 13  Country of NRM Referral         1213 non-null   object
 14  Adult                           1213 non-null   float64
 15  Minor                           1213 non-null   float64
 16  Exploitation Type               1213 non-null   object
 17  Authority/Agency.1              1213 non-null   object
 18  Type                            1213 non-null   object
 19  Total Number of Referrals       1213 non-null   float64
 20  Positive Conclusive Decisions   1213 non-null   float64
 21  Negative (RG or CD)             1213 non-null   float64
 22  Pending decision (RG or CD)     1213 non-null   float64
 23  Suspended Cases                 1213 non-null   float64
 24  Withdrawn                       1213 non-null   float64
 25  Nationality/ Country of Origin  1213 non-null   object
 26  2014 - 2015 % Change            1213 non-null   object
 27  Claimed Exploitation Type       1213 non-null   object
 28  Trans- gender                   1213 non-null   float64
 29  Total 2016                      1213 non-null   float64
 30  Domestic Servitude              1213 non-null   float64
 31  Labour Exploitation             1213 non-null   float64
 32  Organ Harvesting                1213 non-null   float64
 33  Sexual Exploitation             1213 non-null   float64
 34  Unknown Exploitation            1213 non-null   float64
 35  Total Cases.1                   1213 non-null   object
 36  2015-2016 % Change              1213 non-null   object
 37  Withdrawn from Process          1213 non-null   float64
 38  Transsexual                     1213 non-null   float64
 39  Unknown                         1213 non-null   float64
 40  Total 2015                      1213 non-null   float64
 41  Total Cases.2                   1213 non-null   object
 42  2014-2015 % Change              1213 non-null   object
 43  Authority/Agency.2              1213 non-null   object
 44  Agency Type                     1213 non-null   object
dtypes: float64(21), int64(1), object(23)
memory usage: 426.6+ KB

In [5]:
data2=pd.read_csv('/content/human_trafficking.csv')
data2.head()

<ipython-input-5-d1e383351f1b>:1: DtypeWarning: Columns (54) have mixed types. Specify dtype option on import or set low_memory=False.
  data2=pd.read_csv('/content/human_trafficking.csv')

,yearOfRegistration,Datasource,gender,ageBroad,majorityStatus,majorityStatusAtExploit,majorityEntry,citizenship,meansOfControlDebtBondage,meansOfControlTakesEarnings,...,typeOfSexPrivateSexualServices,typeOfSexConcatenated,isAbduction,RecruiterRelationship,CountryOfExploitation,recruiterRelationIntimatePartner,recruiterRelationFriend,recruiterRelationFamily,recruiterRelationOther,recruiterRelationUnknown
0,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
1,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
2,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
3,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
4,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1

In [6]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48801 entries, 0 to 48800
Data columns (total 63 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   yearOfRegistration                      48801 non-null  int64
 1   Datasource                              48801 non-null  object
 2   gender                                  48801 non-null  object
 3   ageBroad                                48801 non-null  object
 4   majorityStatus                          48801 non-null  object
 5   majorityStatusAtExploit                 48801 non-null  object
 6   majorityEntry                           48801 non-null  object
 7   citizenship                             48801 non-null  object
 8   meansOfControlDebtBondage               48801 non-null  int64
 9   meansOfControlTakesEarnings             48801 non-null  int64
 10  meansOfControlRestrictsFinancialAccess  48801 non-null  int64
 11  meansOfControlThreats                   48801 non-null  int64
 12  meansOfControlPsychologicalAbuse        48801 non-null  int64
 13  meansOfControlPhysicalAbuse             48801 non-null  int64
 14  meansOfControlSexualAbuse               48801 non-null  int64
 15  meansOfControlFalsePromises             48801 non-null  int64
 16  meansOfControlPsychoactiveSubstances    48801 non-null  int64
 17  meansOfControlRestrictsMovement         48801 non-null  int64
 18  meansOfControlRestrictsMedicalCare      48801 non-null  int64
 19  meansOfControlExcessiveWorkingHours     48801 non-null  int64
 20  meansOfControlUsesChildren              48801 non-null  int64
 21  meansOfControlThreatOfLawEnforcement    48801 non-null  int64
 22  meansOfControlWithholdsNecessities      48801 non-null  int64
 23  meansOfControlWithholdsDocuments        48801 non-null  int64
 24  meansOfControlOther                     48801 non-null  int64
 25  meansOfControlNotSpecified              48801 non-null  int64
 26  meansOfControlConcatenated              48801 non-null  object
 27  isForcedLabour                          48801 non-null  int64
 28  isSexualExploit                         48801 non-null  int64
 29  isOtherExploit                          48801 non-null  int64
 30  isSexAndLabour                          48801 non-null  int64
 31  isForcedMarriage                        48801 non-null  int64
 32  isForcedMilitary                        48801 non-null  int64
 33  isOrganRemoval                          48801 non-null  int64
 34  isSlaveryAndPractices                   48801 non-null  int64
 35  typeOfExploitConcatenated               48801 non-null  object
 36  typeOfLabourAgriculture                 48801 non-null  int64
 37  typeOfLabourAquafarming                 48801 non-null  int64
 38  typeOfLabourBegging                     48801 non-null  int64
 39  typeOfLabourConstruction                48801 non-null  int64
 40  typeOfLabourDomesticWork                48801 non-null  int64
 41  typeOfLabourHospitality                 48801 non-null  int64
 42  typeOfLabourIllicitActivities           48801 non-null  int64
 43  typeOfLabourManufacturing               48801 non-null  int64
 44  typeOfLabourMiningOrDrilling            48801 non-null  int64
 45  typeOfLabourPeddling                    48801 non-null  int64
 46  typeOfLabourTransportation              48801 non-null  int64
 47  typeOfLabourOther                       48801 non-null  int64
 48  typeOfLabourNotSpecified                48801 non-null  int64
 49  typeOfLabourConcatenated                48801 non-null  object
 50  typeOfSexProstitution                   48801 non-null  int64
 51  typeOfSexPornography                    48801 non-null  int64
 52  typeOfSexRemoteInteractiveServices      48801 non-null  int64
 53  typeOfSexPrivateSexualServices          48801 non-null  int64
 54  typeOfSexConcatenated                   48801 non-null  object
 55  isAbduction                             48801 non-null  int64
 56  RecruiterRelationship                   48801 non-null  object
 57  CountryOfExploitation                   48801 non-null  object
 58  recruiterRelationIntimatePartner        48801 non-null  int64
 59  recruiterRelationFriend                 48801 non-null  int64
 60  recruiterRelationFamily                 48801 non-null  int64
 61  recruiterRelationOther                  48801 non-null  int64
 62  recruiterRelationUnknown                48801 non-null  int64
dtypes: int64(50), object(13)
memory usage: 23.5+ MB

In [7]:
data2.columns

Index(['yearOfRegistration', 'Datasource', 'gender', 'ageBroad',
       'majorityStatus', 'majorityStatusAtExploit', 'majorityEntry',
       'citizenship', 'meansOfControlDebtBondage',
       'meansOfControlTakesEarnings', 'meansOfControlRestrictsFinancialAccess',
       'meansOfControlThreats', 'meansOfControlPsychologicalAbuse',
       'meansOfControlPhysicalAbuse', 'meansOfControlSexualAbuse',
       'meansOfControlFalsePromises', 'meansOfControlPsychoactiveSubstances',
       'meansOfControlRestrictsMovement', 'meansOfControlRestrictsMedicalCare',
       'meansOfControlExcessiveWorkingHours', 'meansOfControlUsesChildren',
       'meansOfControlThreatOfLawEnforcement',
       'meansOfControlWithholdsNecessities',
       'meansOfControlWithholdsDocuments', 'meansOfControlOther',
       'meansOfControlNotSpecified', 'meansOfControlConcatenated',
       'isForcedLabour', 'isSexualExploit', 'isOtherExploit', 'isSexAndLabour',
       'isForcedMarriage', 'isForcedMilitary', 'isOrganRemoval',
       'isSlaveryAndPractices', 'typeOfExploitConcatenated',
       'typeOfLabourAgriculture', 'typeOfLabourAquafarming',
       'typeOfLabourBegging', 'typeOfLabourConstruction',
       'typeOfLabourDomesticWork', 'typeOfLabourHospitality',
       'typeOfLabourIllicitActivities', 'typeOfLabourManufacturing',
       'typeOfLabourMiningOrDrilling', 'typeOfLabourPeddling',
       'typeOfLabourTransportation', 'typeOfLabourOther',
       'typeOfLabourNotSpecified', 'typeOfLabourConcatenated',
       'typeOfSexProstitution', 'typeOfSexPornography',
       'typeOfSexRemoteInteractiveServices', 'typeOfSexPrivateSexualServices',
       'typeOfSexConcatenated', 'isAbduction', 'RecruiterRelationship',
       'CountryOfExploitation', 'recruiterRelationIntimatePartner',
       'recruiterRelationFriend', 'recruiterRelationFamily',
       'recruiterRelationOther', 'recruiterRelationUnknown'],
      dtype='object')